name: build x86_64-pc-windows-msvc
on: [push]
env:
   PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/etc/eselect/wine/bin
jobs:
  x86_64-pc-windows-msvc:
    runs-on: msvc-wine
    steps:
      - run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - run: git clone ${{ github.server_url }}/${{ github.repository }} ${SHORT_SHA}
      - run: cd ${SHORT_SHA} && git checkout ${{ github.sha }}
      - run: mkdir libarchive && cd libarchive && wget -qO- https://www.burntcomma.com/libarchive-3.6.1-x86_64-pc-windows-msvc.tar.gz | tar -xz
      - run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=msvc-amd64.cmake \
            -DCMAKE_INSTALL_PREFIX=${PWD}/install/debug -DCMAKE_INSTALL_INCLUDEDIR=../include \
            -DLibArchive_ROOT="${PWD}/libarchive/debug" -DLibArchive_INCLUDE_DIR="${PWD}/libarchive/include" \
            -DCMAKE_BUILD_TYPE=Debug \
            -S ${SHORT_SHA} -B debug-work && \
          cmake --build debug-work --parallel `nproc` && \
          cmake --install debug-work
      - run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=msvc-amd64.cmake \
            -DCMAKE_INSTALL_PREFIX=${PWD}/install \
            -DLibArchive_ROOT="${PWD}/libarchive" -DLibArchive_INCLUDE_DIR="${PWD}/libarchive/include" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -S ${SHORT_SHA} -B release-work && \
          cmake --build release-work --parallel `nproc` && \
          cmake --install release-work
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          overwrite: true
          path: |
            install
